---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [1]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT
Azerbaijan,5,6,5,15,26,5,0,0,0,0,10,6,5,15,26,AZE
Bahamas,15,5,2,5,12,0,0,0,0,0,15,5,2,5,12,BAH
Bahrain,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1,BRN
Barbados,11,0,0,1,1,0,0,0,0,0,11,0,0,1,1,BAR
Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,BLR
Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,BEL
Bermuda,17,0,0,1,1,7,0,0,0,0,24,0,0,1,1,BER
Bohemia,3,0,1,3,4,0,0,0,0,0,3,0,1,3,4,BOH
Botswana,9,0,1,0,1,0,0,0,0,0,9,0,1,0,1,BOT
Brazil,21,23,30,55,108,7,0,0,0,0,28,23,30,55,108,BRA
British West Indies,1,0,0,2,2,0,0,0,0,0,1,0,0,2,2,BWI
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL
Burundi,5,1,0,0,1,0,0,0,0,0,5,1,0,0,1,BDI
Cameroon,13,3,1,1,5,1,0,0,0,0,14,3,1,1,5,CMR
Canada,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,CAN
Chile,22,2,7,4,13,16,0,0,0,0,38,2,7,4,13,CHI
China,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526,CHN
Colombia,18,2,6,11,19,1,0,0,0,0,19,2,6,11,19,COL
Costa Rica,14,1,1,2,4,6,0,0,0,0,20,1,1,2,4,CRC
Ivory Coast,12,0,1,0,1,0,0,0,0,0,12,0,1,0,1,CIV
Croatia,6,6,7,10,23,7,4,6,1,11,13,10,13,11,34,CRO
Cuba,19,72,67,70,209,0,0,0,0,0,19,72,67,70,209,CUB
Cyprus,9,0,1,0,1,10,0,0,0,0,19,0,1,0,1,CYP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Spain,22,37,59,35,131,19,1,0,1,2,41,38,59,36,133,ESP
Sri Lanka,16,0,2,0,2,0,0,0,0,0,16,0,2,0,2,SRI
Sudan,11,0,1,0,1,0,0,0,0,0,11,0,1,0,1,SUD
Suriname,11,1,0,1,2,0,0,0,0,0,11,1,0,1,2,SUR
Sweden,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,SWE
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI
Syria,12,1,1,1,3,0,0,0,0,0,12,1,1,1,3,SYR
Chinese Taipei,13,2,7,12,21,11,0,0,0,0,24,2,7,12,21,TPE
Tajikistan,5,0,1,2,3,4,0,0,0,0,9,0,1,2,3,TJK
Tanzania,12,0,2,0,2,0,0,0,0,0,12,0,2,0,2,TAN
Thailand,15,7,6,11,24,3,0,0,0,0,18,7,6,11,24,THA
Togo,9,0,0,1,1,1,0,0,0,0,10,0,0,1,1,TOG
Tonga,8,0,1,0,1,1,0,0,0,0,9,0,1,0,1,TGA
Trinidad and Tobago,16,2,5,11,18,3,0,0,0,0,19,2,5,11,18,TRI
Tunisia,13,3,3,4,10,0,0,0,0,0,13,3,3,4,10,TUN
Turkey,21,39,25,24,88,16,0,0,0,0,37,39,25,24,88,TUR
Uganda,14,2,3,2,7,0,0,0,0,0,14,2,3,2,7,UGA
Ukraine,5,33,27,55,115,6,2,1,4,7,11,35,28,59,122,UKR
United Arab Emirates,8,1,0,0,1,0,0,0,0,0,8,1,0,0,1,UAE
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA
Uruguay,20,2,2,6,10,1,0,0,0,0,21,2,2,6,10,URU
Uzbekistan,5,5,5,10,20,6,1,0,0,1,11,6,5,10,21,UZB
Venezuela,17,2,2,8,12,4,0,0,0,0,21,2,2,8,12,VEN
Vietnam,14,0,2,0,2,0,0,0,0,0,14,0,2,0,2,VIE
Virgin Islands,11,0,1,0,1,7,0,0,0,0,18,0,1,0,1,ISV
Yugoslavia,16,26,29,28,83,14,0,3,1,4,30,26,32,29,87,YUG
Independent Olympic Participants,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3,IOP
Zambia,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2,ZAM
Zimbabwe,12,3,4,1,8,1,0,0,0,0,13,3,4,1,8,ZIM
Mixed team,3,8,5,4,17,0,0,0,0,0,3,8,5,4,17,ZZX

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [2]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [3]:
def answer_one():
    return df[df['Gold']==max(df['Gold'])].index[0]
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [4]:
def answer_two():
    return df[df['Gold']-df['Gold.1']==max(df['Gold']-df['Gold.1'])].index[0]
answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [6]:
"""def answer_three(df):
    #return max((df['Gold']-df['Gold.1']))
    new_df = pd.DataFrame()
    new_df = df[(df['Gold']!=0) & (df['Gold.1']!= 0)]
    return new_df[(new_df['Gold']-new_df['Gold.1'])/new_df['Gold.2'] == max((new_df['Gold']-new_df['Gold.1'])/new_df['Gold.2'])].index[0]

answer_three(df)"""


def answer_three():
    df['diff'] = abs(df['Gold'] - df['Gold.1'])
    # create sub dataframe of only elements with greater than 0 Gold and Gold.1
    sub_df = df[(df['Gold'] > 0) & (df['Gold.1'] > 0)].copy()
    # calculate difference between Gold medals relative to total metal count
    sub_df['rel'] = sub_df['diff'] / sub_df['Gold.2']
    return sub_df[sub_df['rel'] == max(sub_df['rel'])].index[0]

answer_three()

'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [14]:
def answer_four():
    Points = df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']
    return Points
print(answer_four())

Afghanistan                            2
Algeria                               27
Argentina                            130
Armenia                               16
Australasia                           22
Australia                            923
Austria                              569
Azerbaijan                            43
Bahamas                               24
Bahrain                                1
Barbados                               1
Belarus                              154
Belgium                              276
Bermuda                                1
Bohemia                                5
Botswana                               2
Brazil                               184
British West Indies                    2
Bulgaria                             411
Burundi                                3
Cameroon                              12
Canada                               846
Chile                                 24
China                               1120
Colombia                              29
Costa Rica                             7
Ivory Coast                            2
Croatia                               67
Cuba                                 420
Cyprus                                 2
                                    ...
Spain                                268
Sri Lanka                              4
Sudan                                  2
Suriname                               4
Sweden                              1217
Switzerland                          630
Syria                                  6
Chinese Taipei                        32
Tajikistan                             4
Tanzania                               4
Thailand                              44
Togo                                   1
Tonga                                  2
Trinidad and Tobago                   27
Tunisia                               19
Turkey                               191
Uganda                                14
Ukraine                              220
United Arab Emirates                   3
United States                       5684
Uruguay                               16
Uzbekistan                            38
Venezuela                             18
Vietnam                                4
Virgin Islands                         2
Yugoslavia                           171
Independent Olympic Participants       4
Zambia                                 3
Zimbabwe                              18
Mixed team                            38
dtype: int64

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [11]:
census_df = pd.read_csv('census.csv')


census_df[census_df['SUMLEV']==40]

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
68,40,4,9,2,0,Alaska,Alaska,710231,710249,714021,...,-1.173489,-1.946424,-3.915107,-14.438910,-10.407475,0.931274,1.818497,-0.757148,-11.271709,-6.881838
98,40,4,8,4,0,Arizona,Arizona,6392017,6392307,6408208,...,1.327489,5.245740,3.905473,6.219955,6.776501,3.290378,7.337279,6.123606,8.761352,9.335208
114,40,3,7,5,0,Arkansas,Arkansas,2915918,2915958,2922394,...,1.365312,-0.432402,-0.442153,-1.060966,-0.407735,2.326251,0.646395,0.682189,0.226168,0.901928
190,40,4,9,6,0,California,California,37253956,37254503,37334079,...,-1.148464,-1.163788,-1.339869,-0.862856,-1.981572,2.761704,2.647127,2.728645,3.743342,2.656065
249,40,4,8,8,0,Colorado,Colorado,5029196,5029324,5048254,...,5.232828,5.513416,6.903846,7.375183,10.073656,6.968908,7.698805,9.053163,9.764255,12.537918
314,40,1,1,9,0,Connecticut,Connecticut,3574097,3574118,3579717,...,-3.724400,-5.311208,-4.730271,-7.567093,-7.687268,0.775510,-1.066084,-0.278693,-2.376831,-2.463243
323,40,3,5,10,0,Delaware,Delaware,897934,897936,899791,...,2.867721,3.594491,3.169689,5.106051,4.490138,5.332723,6.360496,5.939911,8.245757,7.628452
327,40,3,5,11,0,District of Columbia,District of Columbia,601723,601767,605126,...,11.560071,10.052444,9.457678,1.480094,5.601833,17.028422,15.972111,15.634120,8.378037,12.434838
329,40,3,5,12,0,Florida,Florida,18801310,18804623,18849890,...,5.556307,5.138184,4.847420,6.958576,10.080932,11.364173,10.676030,10.565882,13.478570,16.528676
397,40,3,5,13,0,Georgia,Georgia,9687653,9688681,9713454,...,1.116578,1.820078,-0.607357,2.186504,3.349056,3.389168,4.379947,1.886665,4.999230,6.218396
557,40,4,9,15,0,Hawaii,Hawaii,1360301,1360301,1363980,...,-0.728610,-2.555878,-1.038764,-3.518530,-4.927311,4.234545,4.258593,5.314474,3.203227,2.175422
563,40,4,8,16,0,Idaho,Idaho,1567582,1567652,1570986,...,0.070362,-0.160366,3.118843,5.188461,4.182706,0.958442,0.940183,4.259427,6.500203,5.530535
608,40,2,3,17,0,Illinois,Illinois,12830632,12831549,12841249,...,-5.243330,-5.805172,-5.308960,-7.509147,-8.174675,-3.020410,-3.519051,-2.830379,-4.625216,-5.247030
711,40,2,3,18,0,Indiana,Indiana,6483802,6484229,6490590,...,-1.293568,-1.960149,-0.116258,-1.140002,-2.251702,0.157756,-0.447027,1.542780,0.760457,-0.349081
804,40,2,4,19,0,Iowa,Iowa,3046355,3046869,3050694,...,0.132111,-1.394328,0.199064,0.065466,-1.267049,1.714823,0.263105,2.001342,2.127479,0.789299
904,40,2,4,20,0,Kansas,Kansas,2853118,2853132,2858824,...,-3.136815,-1.761232,-4.259882,-4.723711,-4.482170,-1.377266,0.592752,-2.053656,-2.296651,-1.965206
1010,40,3,6,21,0,Kentucky,Kentucky,4339367,4339349,4347937,...,0.548428,-1.055248,-0.534781,-0.986254,-1.683921,1.724221,0.511968,0.945888,0.649634,-0.009278
1131,40,3,7,22,0,Louisiana,Louisiana,4533372,4533479,4544951,...,0.473667,-0.180411,-0.500478,-1.366682,-1.579018,1.949929,1.422368,1.064221,0.376651,0.196358
1196,40,1,1,23,0,Maine,Maine,1328361,1328361,1327695,...,0.068525,-0.441075,-0.991095,0.485891,-1.291931,0.949565,0.505806,0.004515,1.631420,-0.142879
1213,40,3,5,24,0,Maryland,Maryland,5773552,5773785,5788409,...,0.077369,-1.425490,-1.539388,-2.536397,-4.129281,4.606029,3.039478,3.113104,2.673241,1.100340
1238,40,1,1,25,0,Massachusetts,Massachusetts,6547629,6547817,6565036,...,-0.737051,-1.333275,-0.519504,-1.737085,-3.218558,4.566803,4.015802,5.144020,4.735912,3.203502
1253,40,2,3,26,0,Michigan,Michigan,9883640,9884129,9877369,...,-4.364492,-3.383718,-2.913472,-2.906320,-3.922701,-2.544908,-1.400463,-0.763820,-0.458399,-1.482846
1337,40,2,4,27,0,Minnesota,Minnesota,5303925,5303925,5310903,...,-0.697250,-1.627618,-0.291640,-1.203383,-2.236652,1.661128,0.702797,2.224242,1.638219,0.590314
1425,40,3,6,28,0,Mississippi,Mississippi,2967297,2968103,2970316,...,-1.943071,-1.897828,-1.598223,-3.010150,-4.086354,-1.323400,-0.966185,-0.795096,-2.147243,-3.160827
1508,40,2,4,29,0,Missouri,Missouri,5988927,5988927,5996052,...,-2.236429,-2.235616,-1.291223,-1.342305,-1.439638,-0.974961,-0.774839,0.187254,0.313028,0.241367
1624,40,4,8,30,0,Montana,Montana,989415,989417,990643,...,3.452041,3.567821,5.627961,4.364823,5.124013,4.063591,4.308746,6.292463,5.069555,5.854486
1681,40,2,4,31,0,Nebraska,Nebraska,1826341,1826341,1830025,...,-0.633372,-0.496978,-0.261994,-1.332523,-1.468576,1.171983,1.694266,1.977842,1.188611,1.084894
1775,40,4,8,32,0,Nevada,Nevada,2700551,2700691,2703440,...,-2.733178,5.306838,4.846319,8.333086,9.760302,0.016967,7.924449,7.613377,11.517866,12.956601
1793,40,1,1,33,0,New Hampshire,New Hampshire,1316470,1316466,1316708,...,-1.647026,-0.437922,-1.951549,1.429080,-0.877904,-0.309671,0.937972,-0.509823,3.113946,0.810200
1804,40,1,2,34,0,New Jersey,New Jersey,8791894,8791936,8803881,...,-5.099617,-5.563775,-5.137475,-6.216888,-7.292230,0.457420,-0.353542,0.470243,0.180654,-0.913121
1826,40,4,8,35,0,New Mexico,New Mexico,2059179,2059192,2064741,...,0.044413,-3.419154,-5.109690,-6.758128,-6.402799,1.100660,-1.907270,-3.665188,-5.111616,-4.661594
1860,40,1,2,36,0,New York,New York,19378102,19378087,19402920,...,-4.354557,-5.945385,-5.561401,-8.130297,-7.990563,1.439239,-0.402860,0.407960,-1.334639,-1.205321
1923,40,3,5,37,0,North Carolina,North Carolina,9535483,9535692,9558979,...,3.182925,3.274557,3.917733,3.470870,3.822913,5.057573,5.699028,6.128788,5.849442,6.331622
2024,40,2,4,38,0,North Dakota,North Dakota,672591,672591,674530,...,9.034780,16.009040,22.241532,12.479623,13.314923,10.558471,18.470861,24.449274,14.782061,15.675696
2078,40,2,3,39,0,Ohio,Ohio,11536504,11536725,11540766,...,-3.189870,-3.213719,-1.879172,-1.607649,-2.696806,-1.828451,-1.746963,-0.329701,0.175060,-0.913728
2167,40,3,7,40,0,Oklahoma,Oklahoma,3751351,3751616,3759596,...,1.694623,2.358401,3.652939,1.110563,2.104750,3.012368,4.092682,5.290256,2.921241,3.970249
2245,40,4,9,41,0,Oregon,Oregon,3831074,3831073,3837972,...,2.961404,3.354294,2.530063,5.757015,8.705805,4.520870,4.905797,4.255779,7.779997,10.733510
2282,40,1,2,42,0,Pennsylvania,Pennsylvania,12702379,12702887,12712014,...,-0.523231,-1.371189,-2.420849,-2.640310,-3.251021,1.596325,0.920684,-0.004696,0.170229,-0.442643
2350,40,1,1,44,0,Rhode Island,Rhode Island,1052567,1052931,1053219,...,-6.146099,-4.882502,-4.796582,-3.096174,-4.445802,-2.356211,-1.111085,-0.913906,1.332218,0.032209
2356,40,3,5,45,0,South Carolina,South Carolina,4625364,4625401,4635894,...,3.208207,5.604384,6.026867,8.180121,9.373895,4.314492,7.026983,7.202230,9.465643,10.772926
2403,40,2,4,46,0,South Dakota,South Dakota,814180,814191,816299,...,2.453998,5.233525,5.318171,0.496887,-2.079715,3.999785,7.084127,7.099228,2.460888,-0.098144
2470,40,3,6,47,0,Tennessee,Tennessee,6346105,6346275,6356585,...,2.463663,4.330055,2.043918,3.611647,3.259031,3.706784,5.771333,3.457334,5.222361,4.908398
2566,40,3,7,48,0,Texas,Texas,25145561,25146105,25244363,...,4.527491,5.484904,4.446476,6.072953,6.248252,7.616364,8.660719,7.739851,9.780487,9.978697
2821,40,4,8,49,0,Utah,Utah,2763885,2763888,2775426,...,-0.329765,-0.029968,2.107281,-0.104306,3.132103,1.428861,1.773733,4.026022,2.069019,5.300638
2851,40,1,1,50,0,Vermont,Vermont,625741,625745,625984,...,-0.705692,-2.623924,-0.828064,-2.384568,-3.548825,0.282596,-1.469972,0.430784,-0.937877,-2.089704
2866,40,3,5,51,0,Virginia,Virginia,8001024,8001045,8025787,...,1.360760,0.614199,0.346268,-2.197521,-2.849964,5.004781,4.923775,4.447050,2.315622,1.793779
3000,40,4,9,53,0,Washington,Washington,6724540,6724543,6743060,...,3.454740,1.941180,2.212454,3.964679,5.732807,6.412660,5.351692,5.671575,7.840731,9.653974
3040,40,3,5,54,0,West Virginia,West Virginia,1852994,1853011,1854225,...,0.563468,0.561000,-1.419148,-2.242191,-2.537316,1.112377,1.168345,-0.788296,-1.516045,-1.808887
3096,40,2,3,55,0,Wisconsin,Wisconsin,5686986,5687289,5690204,...,-1.088077,-1.665772,-1.328675,-1.641820,-2.700254,-0.057895,-0.510312,-0.070444,-0.164130,-1.213969
3169,40,4,8,56,0,Wyoming,Wyoming,563626,563767,564516,...,-0.381530,9.636214,4.487115,-4.788275,-3.221091,0.289680,10.694870,5.440390,-3.727831,-2.091573

In [43]:
def answer_five():

    mask = (census_df.SUMLEV == 50)
    max_index = census_df[mask].groupby('STNAME')['CTYNAME'].count().idxmax()
    return max_index
answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [15]:
"""def answer_six(census_df):

    census_df = census_df[census_df['SUMLEV']==50]
    #print (census_df.nlargest(9,'CENSUS2010POP')[['STNAME','CTYNAME','CENSUS2010POP']])
    #census_df = census_df['CENSUS2010POP'].groupby('STNAME').apply(lambda x : x.nalrgest(3, 'CENSUS2010POP').sum())
    return list(census_df.groupby('STNAME').apply(lambda x : x.nlargest(3 , 'CENSUS2010POP')['CENSUS2010POP'].sum()).nlargest(3).index)
answer_six(census_df)"""

def answer_six():
    df1 = pd.DataFrame(census_df.where(census_df['SUMLEV'] == 50).groupby(['STNAME'])['POPESTIMATE2015'].nlargest(3))
    df1 = df1.reset_index()

    return list(df1.groupby(['STNAME']).sum()['POPESTIMATE2015'].nlargest(3).index)

answer_six()

['California', 'Texas', 'Illinois']

## Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [13]:
"""def answer_seven(census_df):
    census_df = census_df[census_df['SUMLEV']==50]
    census_df.set_index(['STNAME', 'CTYNAME'], inplace = True)
    census_df = census_df.loc[:, 'POPESTIMATE2010':'POPESTIMATE2015']
    census_df = census_df[census_df.max(axis=1) - census_df.min(axis =1)==max(census_df.max(axis=1) - census_df.min(axis =1))]
    census_df.reset_index(inplace=True)
    return list(census_df['CTYNAME'])[0]
answer_seven(census_df)"""

def answer_seven():
    d = census_df[census_df.SUMLEV==50].copy()
    d['max'] = d[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].max(axis=1)
    d['min'] = d[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].min(axis=1)
    d['diff'] = d['max'] - d['min']

    return d[d['diff'] == d['diff'].max()].iloc[0]['CTYNAME']

answer_seven()

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [14]:
def answer_eight(census_df):
    #census_df = census_df[census_df['SUMLEV']==50]
    #census_df = census_df[(census_df['REGION']==1) | (census_df['REGION']==2)]
    #census_df = census_df[census_df['POPESTIMATE2015']>census_df['POPESTIMATE2014']]
    #census_df = census_df[census_df['CTYNAME'].str.startswith("Washington")][['STNAME','CTYNAME']]
    
    #return census_df
    return census_df[((census_df['REGION'] == 1) | (census_df['REGION'] == 1)) & (census_df['CTYNAME'].str.startswith("Washington"))].loc[:,['STNAME','CTYNAME']]
answer_eight(census_df)

            STNAME            CTYNAME
1211         Maine  Washington County
1918      New York  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
2863       Vermont  Washington County